sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBhREFeQkYmRqfacVzi
    access-key-secret: VTeNyVAdcmYom6mOBudBgSvDTDMRJG
    bucket-name: sky-me

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wx237a7a740b5a5e77
    secret: 94c913225fab604da5c6dcdce3e82a3b
